### ISSUE TITLE
ecs logging can throw an NPE

### ISSUE THREAD

**Issue by johnsweetescott** [elastic/ecs-logging-java#44]
ecs-logging can throw an NPE, as per stack trace below.
```
Caused by: java.lang.NullPointerException                                                                                                                 [849/1871]        at co.elastic.logging.JsonUtils.quoteAsString(JsonUtils.java:63)

        at co.elastic.logging.EcsJsonSerializer.serializeException(EcsJsonSerializer.java:163)
        at co.elastic.logging.log4j.EcsLayout.format(EcsLayout.java:62)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
        at org.apache.log4j.DailyRollingFileAppender.subAppend(DailyRollingFileAppender.java:369)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.error(Category.java:322)
        at private code
```

**Comment by felixbarny** [comment]
thx for reporting, I've created a PR
