### ISSUE TITLE
Thread crash when parameter is a null value

### ISSUE THREAD

**Issue by Fr33Radical** [elastic/ecs-logging-java#50]
logger.info(markerCLM, new StringMapMessage()
				.with("message", "Test message")
				.with("event.action", null)
				.with("event.category", "General"));

This will crash. It is not supposed to happen, but sometimes a parameter can be null unexpectedly.
It would be sad that a thread crash because of a null value.

Mostly, I think it crash because of the Class StringMapMessage who does not allow null as a value.

A short term solution would be to add ParameterizedMessage around the value as :
.with("event.action", new ParameterizedMessage(null)) and it returns the string "null".

Should we use another type rather than StringMapMessage? (**With Java 8**)

I thought 0.1.3 would fix it, but it looks like it was something else.

**Comment by felixbarny** [comment]
Could you provide the stack trace of the Exception?

**Comment by Fr33Radical** [comment]
java.lang.IllegalArgumentException: No value provided for key event.action
	at org.apache.logging.log4j.message.MapMessage.put(MapMessage.java:202)
	at org.apache.logging.log4j.message.MapMessage.with(MapMessage.java:760)
	at clm.testCLM.testLogConsole(testCLM.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by Fr33Radical** [comment]
HashMap allows null value but it won't map into the json fields as StringMapMessage does.

**Comment by Fr33Radical** [comment]
```
Map<String, String> hashMap = new HashMap<String, String>()
		{{
		     put("message", (new ParameterizedMessage(multiparameters, "8", "1", "This", "is", "my", null, "parameter", "!")).getFormattedMessage());
		     put("event.action", null);
		     put("event.category", "General");
		}};
		StringMapMessage test = new StringMapMessage().newInstance(hashMap);
		logger.info(markerCLM, test);
```

That is working but far less beautiful. What do you think?

**Comment by felixbarny** [comment]
Have you tried `logger.info((new ObjectMessage(map));`? Make sure that Jackson is on the classpath as well.

**Comment by Fr33Radical** [comment]
<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.10.1</version>
		</dependency>

That one? Because he does not have ObjectMessage in it.
How would you instantiate map?
Could it ObjectMessage().with...?

**Comment by felixbarny** [comment]
ObjectMessage is part of the log4j API.

> How would you instantiate map? It crash at the initialization.

Like that:

```java
Map<String, Object> map = new HashMap<>();
map.put("foo", "bar");
logger.info(new ObjectMessage(map));
```

**Comment by Fr33Radical** [comment]
I report the issue to Log4j2 : 
https://issues.apache.org/jira/browse/LOG4J2-2721
